services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $filesStorage: '@contao.filesystem.virtual.files'
            $projectDir: '%kernel.project_dir%'
            $uploadPath: '%contao.upload_path%'

    Markocupic\ContaoMultifileDownload\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,Resources}
